trigger:
  branches:
    include:
      - main

pool:
  name: default  # Uses the default agent pool

variables:
- group: Hub_Spoke  # Contains ARM_CLIENT_ID, etc.

stages:
- stage: Terraform
  jobs:
  - job: InitPlanApply
    steps:
    - checkout: self

    # Authenticate with Azure using service connection
    - task: AzureCLI@2
      inputs:
        azureSubscription: 'AzureConnection-PTutorial'
        scriptType: 'pscore'
        scriptLocation: 'inlineScript'
        inlineScript: |
          # Print Terraform version
          terraform version

          # Set Azure authentication environment variables
          $env:ARM_CLIENT_ID       = "$(ARM_CLIENT_ID)"
          $env:ARM_CLIENT_SECRET   = "$(ARM_CLIENT_SECRET)"
          $env:ARM_TENANT_ID       = "$(ARM_TENANT_ID)"
          $env:ARM_SUBSCRIPTION_ID = "$(ARM_SUBSCRIPTION_ID)"

          # Run Terraform commands
          terraform init -reconfigure
          terraform plan
          terraform apply -auto-approve
