trigger:
  branches:
    include:
      - main

pool:
  name: default  # your agent pool

stages:
- stage: Terraform
  jobs:
  - job: InitPlanApply
    steps:
    - checkout: self

    # Download and install Terraform 1.5.6
    - task: PowerShell@2
      displayName: 'Install Terraform 1.5.6'
      inputs:
        targetType: 'inline'
        script: |
          Write-Host "Downloading Terraform 1.5.6..."
          Invoke-WebRequest -Uri https://releases.hashicorp.com/terraform/1.5.6/terraform_1.5.6_windows_amd64.zip -OutFile terraform.zip

          $dest = "$Env:USERPROFILE\terraform"
          if (-Not (Test-Path -Path $dest)) {
            New-Item -ItemType Directory -Path $dest
          }

          Expand-Archive -Path terraform.zip -DestinationPath $dest -Force
          Write-Host "Terraform extracted to $dest"

          # Persist the path for use in next task
          echo "##vso[task.setvariable variable=TerraformPath]$dest"

    # Authenticate to Azure and run Terraform using installed binary
    - task: AzureCLI@2
      displayName: 'Terraform Init, Plan, Apply'
      inputs:
        azureSubscription: 'AzureConnection-PTutorial'   # your service connection
        scriptType: 'ps'
        scriptLocation: 'inlineScript'
        inlineScript: |
          $env:PATH = "$(TerraformPath);$env:PATH"
          cd "$(System.DefaultWorkingDirectory)"
          terraform version
          terraform init -reconfigure
          terraform plan
          terraform apply -auto-approve
