trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'windows-latest'

variables:
- group: Hub-Spoke-Var-Grp  # ARM_CLIENT_ID, ARM_CLIENT_SECRET, etc.

stages:
- stage: Terraform
  jobs:
  - job: TerraformJob
    displayName: 'Terraform Init, Plan, Apply'
    steps:

    - checkout: self  # This will checkout your GitHub repo into the agent

    - task: PowerShell@2
      displayName: 'Install Terraform 1.5.6'
      inputs:
        targetType: 'inline'
        script: |
          $version = "1.5.6"
          $url = "https://releases.hashicorp.com/terraform/$version/terraform_${version}_windows_amd64.zip"
          Invoke-WebRequest -Uri $url -OutFile "$env:USERPROFILE\terraform.zip"
          Expand-Archive -Path "$env:USERPROFILE\terraform.zip" -DestinationPath "$env:USERPROFILE\terraform" -Force
          $env:PATH = "$env:USERPROFILE\terraform;$env:PATH"
          terraform -version

    - task: AzureCLI@2
      displayName: 'Terraform Init & Apply'
      inputs:
        azureSubscription: 'AzureConnection-PTutorial'  # The service connection name
        scriptType: 'ps'
        scriptLocation: 'inlineScript'   # Important to specify for inline scripts!
        inlineScript: |
          # Set Terraform Azure environment variables
          $env:ARM_CLIENT_ID = "$(ARM_CLIENT_ID)"
          $env:ARM_CLIENT_SECRET = "$(ARM_CLIENT_SECRET)"
          $env:ARM_SUBSCRIPTION_ID = "$(ARM_SUBSCRIPTION_ID)"
          $env:ARM_TENANT_ID = "$(ARM_TENANT_ID)"

          # Add terraform folder to PATH (new process so need to add again)
          $env:PATH = "$env:USERPROFILE\terraform;$env:PATH"

          # Move to repo directory
          cd "$(System.DefaultWorkingDirectory)"

          terraform init -reconfigure
          terraform plan -out=tfplan
          terraform apply -auto-approve tfplan
