trigger:
  branches:
    include:
      - main

pool:
  name: default  # Your Azure DevOps agent pool

stages:
- stage: Terraform
  jobs:
  - job: InitPlanApply
    steps:
    - checkout: self

    - task: AzureCLI@2
      inputs:
        azureSubscription: 'AzureConnection-PTutorial'  # Your service connection
        scriptType: 'ps'
        scriptLocation: 'inlineScript'
        inlineScript: |
          # Show Terraform version
          terraform version

          # Initialize Terraform (reads backend config from your .tf files)
          terraform init -reconfigure

          # Run Terraform plan
          terraform plan

          # Apply changes automatically
          terraform apply -auto-approve
