trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'windows-latest'

variables:
- group: Hub-Spoke-Var-Grp  # Contains ARM_CLIENT_ID, ARM_CLIENT_SECRET, ARM_SUBSCRIPTION_ID, ARM_TENANT_ID

stages:
- stage: Terraform
  jobs:
  - job: TerraformJob
    displayName: 'Terraform Init, Plan, Apply'
    steps:

    - checkout: self

    # Install Terraform (if not already present in agent)
    - task: PowerShell@2
      displayName: 'Install Terraform 1.5.6'
      inputs:
        targetType: 'inline'
        script: |
          $version = "1.5.6"
          Invoke-WebRequest -Uri "https://releases.hashicorp.com/terraform/$version/terraform_${version}_windows_amd64.zip" -OutFile "terraform.zip"
          Expand-Archive -Path "terraform.zip" -DestinationPath "$env:USERPROFILE\terraform" -Force
          $env:PATH = "$env:USERPROFILE\terraform;$env:PATH"
          terraform -version

    # Terraform Init/Plan/Apply
    - task: AzureCLI@2
      displayName: 'Terraform Init & Apply'
      inputs:
        azureSubscription: 'AzureConnection-PTutorial'
        scriptType: 'ps'
        targetType: 'inline'
        script: |
          $env:ARM_CLIENT_ID = "$(ARM_CLIENT_ID)"
          $env:ARM_CLIENT_SECRET = "$(ARM_CLIENT_SECRET)"
          $env:ARM_SUBSCRIPTION_ID = "$(ARM_SUBSCRIPTION_ID)"
          $env:ARM_TENANT_ID = "$(ARM_TENANT_ID)"

          cd "$(System.DefaultWorkingDirectory)"

          terraform init -reconfigure
          terraform plan -out=tfplan
          terraform apply -auto-approve tfplan
