trigger:
  branches:
    include:
      - main

pool:
  name: 'Default'  # your agent pool

stages:
- stage: Terraform
  jobs:
  - job: InitPlanApply
    steps:
    - checkout: self

    # Install Terraform 1.12.2
    - task: PowerShell@2
      displayName: 'Install Terraform 1.12.2'
      inputs:
        targetType: 'inline'
        script: |
          Write-Host "Downloading Terraform 1.12.2"
          Invoke-WebRequest -Uri https://releases.hashicorp.com/terraform/1.12.2/terraform_1.12.2_windows_amd64.zip -OutFile terraform.zip

          $dest = "$Env:USERPROFILE\terraform"
          if (-Not (Test-Path -Path $dest)) {
            New-Item -ItemType Directory -Path $dest | Out-Null
          }

          Expand-Archive -Path terraform.zip -DestinationPath $dest -Force

          # Add terraform to PATH for this session
          $env:PATH = "$dest;$env:PATH"

          terraform version

    # Run Terraform with explicit SP credentials
    - task: AzureCLI@2
      displayName: 'Terraform init, plan and apply'
      inputs:
        azureSubscription: 'AzureConnection-PTutorial'  # still needed to set context
        scriptType: 'ps'
        scriptLocation: 'inlineScript'
        inlineScript: |
          $env:ARM_CLIENT_ID = '$(ARM_CLIENT_ID)'
          $env:ARM_CLIENT_SECRET = '$(ARM_CLIENT_SECRET)'
          $env:ARM_TENANT_ID = '$(ARM_TENANT_ID)'
          $env:ARM_SUBSCRIPTION_ID = '$(ARM_SUBSCRIPTION_ID)'

          terraform init -reconfigure
          terraform plan
          terraform apply -auto-approve
