trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'windows-latest'

variables:
- group: Hub-Spoke-Var-Grp  # Contains ARM_CLIENT_ID, ARM_CLIENT_SECRET, ARM_SUBSCRIPTION_ID, ARM_TENANT_ID

stages:
- stage: Terraform
  jobs:
  - job: TerraformJob
    displayName: 'Terraform Init, Plan, Apply'
    steps:

    - checkout: self

    # Install Terraform 1.5.6
    - powershell: |
        $version = "1.5.6"
        $terraformUrl = "https://releases.hashicorp.com/terraform/$version/terraform_${version}_windows_amd64.zip"
        Invoke-WebRequest -Uri $terraformUrl -OutFile "terraform.zip"
        Expand-Archive -Path "terraform.zip" -DestinationPath "$env:USERPROFILE\terraform" -Force
        Add-Content -Path $env:GITHUB_PATH -Value "$env:USERPROFILE\terraform"
        $env:PATH = "$env:USERPROFILE\terraform;$env:PATH"
        terraform -version
      displayName: 'Install Terraform 1.5.6'

    # Terraform Init, Plan and Apply using Azure CLI
    - task: AzureCLI@2
      displayName: 'Terraform Init & Apply'
      inputs:
        azureSubscription: 'AzureConnection-PTutorial'
        scriptType: 'ps'
        targetType: 'inline'
        script: |
          # Export environment variables for Terraform Azure Provider
          $env:ARM_CLIENT_ID = "$(ARM_CLIENT_ID)"
          $env:ARM_CLIENT_SECRET = "$(ARM_CLIENT_SECRET)"
          $env:ARM_SUBSCRIPTION_ID = "$(ARM_SUBSCRIPTION_ID)"
          $env:ARM_TENANT_ID = "$(ARM_TENANT_ID)"

          # Move to working directory
          cd "$(System.DefaultWorkingDirectory)"

          # Ensure Terraform binary is found
          $env:PATH = "$env:USERPROFILE\terraform;$env:PATH"

          # Terraform commands
          terraform init -reconfigure
          terraform plan -out=tfplan
          terraform apply -auto-approve tfplan
