trigger:
  branches:
    include:
      - main

pool:
  name: default  # Use your defined DevOps agent pool

variables:
- group: TerraformSecrets  # Your secure values for Azure auth

stages:
- stage: Terraform
  jobs:
  - job: InitPlanApply
    steps:
    - checkout: self

    - task: PowerShell@2
      inputs:
        targetType: 'inline'
        script: |
          # Confirm Terraform is pre-installed
          terraform version

          # Set environment variables for Azure provider
          $env:ARM_CLIENT_ID       = "$(ARM_CLIENT_ID)"
          $env:ARM_CLIENT_SECRET   = "$(ARM_CLIENT_SECRET)"
          $env:ARM_TENANT_ID       = "$(ARM_TENANT_ID)"
          $env:ARM_SUBSCRIPTION_ID = "$(ARM_SUBSCRIPTION_ID)"

          # Terraform commands from root directory
          terraform init -reconfigure
          terraform plan
          terraform apply -auto-approve
