trigger:
  branches:
    include:
      - main

pool:
  name: default

stages:
- stage: Terraform
  jobs:
  - job: InitPlanApply
    steps:
    - checkout: self

    - task: PowerShell@2
      displayName: 'Install Terraform 1.5.6'
      inputs:
        targetType: 'inline'
        script: |
          Invoke-WebRequest -Uri https://releases.hashicorp.com/terraform/1.5.6/terraform_1.5.6_windows_amd64.zip -OutFile terraform.zip
          $dest = "$Env:USERPROFILE\terraform"
          if (-Not (Test-Path -Path $dest)) {
            New-Item -ItemType Directory -Path $dest
          }
          Expand-Archive -Path terraform.zip -DestinationPath $dest -Force
          $env:PATH = "$dest;$env:PATH"
          terraform version

    - task: AzureCLI@2
      displayName: 'Run Terraform'
      inputs:
        azureSubscription: 'AzureConnection-PTutorial'
        scriptType: 'ps'
        scriptLocation: 'inlineScript'
        inlineScript: |
          cd "$(System.DefaultWorkingDirectory)"
          terraform init -reconfigure
          terraform plan
          terraform apply -auto-approve
