trigger:
  branches:
    include:
      - main

pool:
  name: default  # Use your agent pool here

stages:
- stage: Terraform
  jobs:
  - job: InitPlanApply
    steps:
    - checkout: self

    # Install Terraform 1.12.2 (update version here if needed)
    - task: PowerShell@2
      displayName: 'Install Terraform 1.12.2'
      inputs:
        targetType: 'inline'
        script: |
          Write-Host "Downloading Terraform 1.12.2"
          Invoke-WebRequest -Uri https://releases.hashicorp.com/terraform/1.12.2/terraform_1.12.2_windows_amd64.zip -OutFile terraform.zip

          $dest = "$Env:USERPROFILE\terraform"
          if (-Not (Test-Path -Path $dest)) {
            New-Item -ItemType Directory -Path $dest
          }

          Expand-Archive -Path terraform.zip -DestinationPath $dest -Force

          # Add terraform to PATH for this session
          $env:PATH = "$dest;$env:PATH"

          terraform version

    # Run terraform commands
    - task: AzureCLI@2
      displayName: 'Terraform Init, Plan and Apply'
      inputs:
        azureSubscription: 'AzureConnection-PTutorial'   # your Azure service connection name
        scriptType: 'ps'  # Use PowerShell Core
        scriptLocation: 'inlineScript'
        inlineScript: |
          # Initialize Terraform backend
          terraform init -reconfigure

          # Generate the plan and save to tfplan
          terraform plan -out=tfplan

          # Apply the saved plan
          terraform apply -auto-approve tfplan
